"""Measure the Neon database: table and index sizes, index use, and swap headroom.

    DATABASE_URL=... uv run python scripts/db_sizes.py        writes eval/db_sizes.md

A load builds a complete second copy of the "filed" schema before swapping it in
(docs/decisions.md D10), so the database needs room for two copies. The report compares
twice the schema size with the plan limit (FILED_DB_LIMIT_MB, default 512 for the Neon
free plan). idx_scan counts come from pg_stat_user_indexes since the last load (each load
creates new indexes), so read them after the site has served traffic for a while.
"""

from __future__ import annotations

import os
from pathlib import Path

import psycopg

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "eval" / "db_sizes.md"
MB = 1024 * 1024


def measure(url: str, schema: str = "filed") -> dict:
    with psycopg.connect(url) as pg:
        tables = pg.execute(
            """SELECT c.relname, c.reltuples::bigint, pg_table_size(c.oid), pg_indexes_size(c.oid)
                 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
                WHERE n.nspname = %s AND c.relkind = 'r' ORDER BY 3 + 4 DESC""",
            [schema],
        ).fetchall()
        indexes = pg.execute(
            """SELECT s.relname, s.indexrelname, pg_relation_size(s.indexrelid), s.idx_scan,
                      pg_get_indexdef(s.indexrelid)
                 FROM pg_stat_user_indexes s WHERE s.schemaname = %s
                ORDER BY 3 DESC""",
            [schema],
        ).fetchall()
        db = pg.execute("SELECT pg_database_size(current_database())").fetchone()[0]
        years = pg.execute(
            f"SELECT fiscal_year, count(*) FROM {schema}.lca_cube GROUP BY 1 ORDER BY 1"
        ).fetchall()
    return {"tables": tables, "indexes": indexes, "database": db, "cube_rows_by_year": years}


def report(m: dict, limit_mb: int) -> str:
    schema_bytes = sum(t[2] + t[3] for t in m["tables"])
    lines = [
        "# Database size",
        "",
        "Generated by `uv run python scripts/db_sizes.py`.",
        "",
        f"- Schema `filed`: **{schema_bytes / MB:,.1f} MB** (tables and indexes)",
        f"- Whole database: {m['database'] / MB:,.1f} MB",
        f"- Needed during a load (two copies): {2 * schema_bytes / MB:,.1f} MB of {limit_mb} MB",
        f"- Headroom: {limit_mb - 2 * schema_bytes / MB:,.1f} MB",
        "",
        "| Table | Rows (estimate) | Table MB | Index MB |",
        "| --- | ---: | ---: | ---: |",
    ]
    lines += [f"| {t} | {r:,} | {ts / MB:,.1f} | {ix / MB:,.1f} |" for t, r, ts, ix in m["tables"]]
    lines += ["", "| Index | MB | Scans since load | Definition |", "| --- | ---: | ---: | --- |"]
    lines += [
        f"| {i} | {sz / MB:,.2f} | {scans:,} | `{d}` |" for _, i, sz, scans, d in m["indexes"]
    ]
    lines += ["", "| Fiscal year | lca_cube rows |", "| --- | ---: |"]
    lines += [f"| {fy} | {n:,} |" for fy, n in m["cube_rows_by_year"]]
    return "\n".join(lines) + "\n"


def main() -> None:
    url = os.environ.get("DATABASE_URL_DIRECT") or os.environ["DATABASE_URL"]
    text = report(measure(url), int(os.environ.get("FILED_DB_LIMIT_MB", "512")))
    OUT.write_text(text)
    print(text)


if __name__ == "__main__":
    main()
