"""Reconcile Neon against the raw DOL files with a separate code path.

For every loaded fiscal year, count certified, withdrawn and denied cases straight from the
raw xlsx files using pandas (calamine reader), with no DuckDB and no code from etl/, and
compare with the sums of filed.lca_year in Neon. Writes eval/reconcile.md.

The pandas path re-implements the two rules the pipeline applies, independently:
- drop the formatted-but-empty rows at the bottom of a sheet (no CASE_NUMBER);
- within a fiscal year, a case in several quarterly files keeps its latest quarter's row.

Run: uv run python scripts/reconcile.py   (needs DATABASE_URL, or DATABASE_URL_DIRECT)
"""

from __future__ import annotations

import os
import re
from pathlib import Path

import pandas as pd
import psycopg

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw" / "dol"
OUT = ROOT / "eval" / "reconcile.md"


def raw_files() -> dict[int, list[tuple[int, Path]]]:
    by_year: dict[int, list[tuple[int, Path]]] = {}
    for p in sorted(RAW.glob("LCA_Disclosure_Data_FY*_Q*.xlsx")):
        fy, q = map(int, re.search(r"FY(\d{4})_Q(\d)", p.name).groups())
        by_year.setdefault(fy, []).append((q, p))
    # FY2026 has a single cumulative Q3 file; earlier years have one file per quarter.
    return by_year


def pandas_counts(files: list[tuple[int, Path]]) -> dict[str, int]:
    frames = []
    for q, p in files:
        df = pd.read_excel(p, engine="calamine", usecols=["CASE_NUMBER", "CASE_STATUS"], dtype=str)
        df = df[df["CASE_NUMBER"].notna() & (df["CASE_NUMBER"].str.strip() != "")]
        df["q"] = q
        frames.append(df)
    df = pd.concat(frames)
    df = df.sort_values("q").drop_duplicates("CASE_NUMBER", keep="last")
    status = df["CASE_STATUS"].str.strip().str.lower().str.replace(r"\s*-\s*", "-", regex=True)
    return {
        "filed": len(df),
        "certified": int((status == "certified").sum()),
        "withdrawn": int(status.isin(["withdrawn", "certified-withdrawn"]).sum()),
        "denied": int((status == "denied").sum()),
    }


def db_counts() -> dict[int, dict[str, int]]:
    url = os.environ.get("DATABASE_URL_DIRECT") or os.environ["DATABASE_URL"]
    with psycopg.connect(url) as pg:
        rows = pg.execute(
            "SELECT fiscal_year, sum(filed), sum(certified), sum(withdrawn), sum(denied) "
            "FROM filed.lca_year GROUP BY 1 ORDER BY 1"
        ).fetchall()
    return {
        r[0]: dict(zip(["filed", "certified", "withdrawn", "denied"], map(int, r[1:]), strict=True))
        for r in rows
    }


def main() -> None:
    db = db_counts()
    lines = [
        "# Reconcile",
        "",
        "Generated by `uv run python scripts/reconcile.py`. Case counts per fiscal year",
        "computed from the raw DOL xlsx files with pandas (a separate code path from the",
        "DuckDB pipeline), compared with the sums in the Neon database the site reads.",
        "",
        "| Fiscal year | Measure | Raw files (pandas) | Database | Difference |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    total_diff = 0
    for fy, files in raw_files().items():
        raw = pandas_counts(files)
        for k in ["filed", "certified", "withdrawn", "denied"]:
            d = db.get(fy, {}).get(k, 0) - raw[k]
            total_diff += abs(d)
            lines.append(f"| {fy} | {k} | {raw[k]:,} | {db.get(fy, {}).get(k, 0):,} | {d:,} |")
        print(fy, raw, db.get(fy))
    lines += ["", f"**Total absolute difference: {total_diff:,}**", ""]
    OUT.write_text("\n".join(lines))
    print("total difference:", total_diff)


if __name__ == "__main__":
    main()
