"""Wage annualization.

Offered and prevailing wages in the LCA files come in five units. Every wage is
converted to a yearly figure with a fixed multiplier. Annualized values outside
[WAGE_MIN, WAGE_MAX] are almost always unit errors (an hourly rate entered as
"Year", a yearly salary entered as "Hour"), so those rows are kept but flagged
and left out of wage statistics.
"""

from __future__ import annotations

import logging

import duckdb

log = logging.getLogger(__name__)

MULTIPLIERS: dict[str, int] = {
    "Year": 1,
    "Month": 12,
    "Bi-Weekly": 26,
    "Week": 52,
    "Hour": 2080,
}

WAGE_MIN = 15_000
WAGE_MAX = 1_000_000


def _unit_key(unit: str | None) -> str | None:
    """Match a raw unit string to a MULTIPLIERS key, ignoring case and spacing."""
    if unit is None:
        return None
    u = unit.strip().lower().replace(" ", "").replace("_", "-")
    for key in MULTIPLIERS:
        if u == key.lower():
            return key
    if u in {"biweekly", "bi-week"}:
        return "Bi-Weekly"
    return None


def annualize(value: float | None, unit: str | None) -> float | None:
    """Return the yearly equivalent of a wage, or None if value or unit is unusable."""
    key = _unit_key(unit)
    if value is None or key is None:
        return None
    return float(value) * MULTIPLIERS[key]


def is_valid_annual(annual: float | None) -> bool:
    """True when an annualized wage is inside the plausible range."""
    return annual is not None and WAGE_MIN <= annual <= WAGE_MAX


def annualize_sql(value_col: str, unit_col: str) -> str:
    """DuckDB expression that annualizes value_col using unit_col (same rules as annualize)."""
    unit = f"lower(replace(replace(trim({unit_col}), ' ', ''), '_', '-'))"
    cases = " ".join(f"WHEN '{k.lower()}' THEN {m}" for k, m in MULTIPLIERS.items())
    return (
        f"(CAST({value_col} AS DOUBLE) * CASE "
        f"CASE WHEN {unit} = 'biweekly' THEN 'bi-weekly' ELSE {unit} END "
        f"{cases} ELSE NULL END)"
    )


def add_annual_wages(con: duckdb.DuckDBPyConnection, table: str = "lca") -> dict[str, int]:
    """Add wage_annual, pw_annual and wage_valid columns to `table` and log exclusions.

    wage_annual uses wage_from, the lower bound of the offered range, which is always
    filled in; wage_to is often blank. See docs/decisions.md.
    """
    have = {r[0] for r in con.execute(f"DESCRIBE {table}").fetchall()}
    added = [c for c in ("wage_annual", "pw_annual", "wage_valid") if c in have]
    exclude = f"EXCLUDE ({', '.join(added)})" if added else ""
    con.execute(f"""
        CREATE OR REPLACE TABLE {table} AS
        SELECT * {exclude},
            {annualize_sql("wage_from", "wage_unit")} AS wage_annual,
            {annualize_sql("prevailing_wage", "pw_unit")} AS pw_annual
        FROM {table}
    """)
    con.execute(f"""
        CREATE OR REPLACE TABLE {table} AS
        SELECT *,
            coalesce(wage_annual BETWEEN {WAGE_MIN} AND {WAGE_MAX}, false) AS wage_valid
        FROM {table}
    """)
    rows = con.execute(f"""
        SELECT count(*) AS total,
               count(wage_annual) AS with_wage,
               count(*) FILTER (WHERE wage_annual < {WAGE_MIN}) AS below_min,
               count(*) FILTER (WHERE wage_annual > {WAGE_MAX}) AS above_max,
               count(*) FILTER (WHERE wage_annual IS NULL) AS unusable
        FROM {table}
    """).fetchone()
    keys = ["total", "with_wage", "below_min", "above_max", "unusable"]
    stats = dict(zip(keys, rows, strict=True))
    log.info(
        "wages: %d rows, %d excluded as below $%d, %d above $%d, %d with no usable wage or unit",
        stats["total"],
        stats["below_min"],
        WAGE_MIN,
        stats["above_max"],
        WAGE_MAX,
        stats["unusable"],
    )
    return stats


def write_report(con: duckdb.DuckDBPyConnection, path, table: str = "lca") -> None:
    """eval/wages.md: excluded wage rows per fiscal year and per unit."""
    by_year = con.execute(f"""
        SELECT fiscal_year, count(*),
               count(*) FILTER (WHERE wage_annual < {WAGE_MIN}),
               count(*) FILTER (WHERE wage_annual > {WAGE_MAX}),
               count(*) FILTER (WHERE wage_annual IS NULL)
        FROM {table} GROUP BY 1 ORDER BY 1
    """).fetchall()
    by_unit = con.execute(f"""
        SELECT coalesce(wage_unit, '(blank)'), count(*),
               count(*) FILTER (WHERE NOT wage_valid)
        FROM {table} GROUP BY 1 ORDER BY 2 DESC
    """).fetchall()
    lines = [
        "# Wage annualization",
        "",
        "Generated by `uv run filed wages`. Offered wage (WAGE_RATE_OF_PAY_FROM) annualized with",
        "Year x1, Month x12, Bi-Weekly x26, Week x52, Hour x2080. Rows outside",
        f"${WAGE_MIN:,} to ${WAGE_MAX:,} are kept but left out of wage statistics.",
        "",
        "| Fiscal year | Cases | Under $15,000 | Over $1,000,000 | No usable wage | Excluded |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for fy, n, lo, hi, none in by_year:
        share = (lo + hi + none) / n
        lines.append(f"| {fy} | {n:,} | {lo:,} | {hi:,} | {none:,} | {share:.2%} |")
    lines += ["", "| Unit | Cases | Excluded |", "| --- | ---: | ---: |"]
    lines += [f"| {u} | {n:,} | {x:,} |" for u, n, x in by_unit]
    salary_wrong_unit, excluded = con.execute(f"""
        SELECT count(*) FILTER (WHERE wage_unit <> 'Year' AND wage_from >= {WAGE_MIN}),
               count(*)
        FROM {table} WHERE NOT wage_valid
    """).fetchone()
    lines += [
        "",
        f"{salary_wrong_unit:,} of the {excluded:,} excluded rows have an offered wage of at least",
        f"${WAGE_MIN:,} with a unit other than Year: a yearly salary entered per hour, week,",
        "two weeks or month (for example 117,915 per Hour for a Principal Systems Engineer",
        "whose prevailing wage is 117,915 per Year).",
        "",
    ]
    path.write_text("\n".join(lines))
